apiVersion: apps/v1 
kind: Deployment
metadata:
  name: testcdsc-deployment
spec:
  selector:
    matchLabels:
      app: testcdsc
  replicas: 2
  template:
    metadata:
      labels:
        app: testcdsc
    spec:
     containers:
      - name: testcdsc
        image: testcd.azurecr.io/testcdsc:latest
        ports:
        - containerPort: 8080
     imagePullSecrets:
      - name: acrauth
---
apiVersion: v1
kind: Service
metadata:
  name: testcdsc-service
spec:
  selector:
    app: testcdsc
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testcdsc-ingress
spec:
  backend:
    serviceName: testcdsc
    servicePort: 8080
